project:
  type: website
  output-dir: docs

website:
  title: "Games of Horror for Open Science Training"
  search: false
  site-url: https://ghostcollective.github.io
  repo-url: https://github.com/ghostCollective/ghostcollective.github.io
  repo-actions: [edit, issue]
  page-footer: 
    center: Powered by Quarto and a love for Open Science

  navbar:
    title: false
    logo: img/ghost-logo.png
    right: 
#      - href: games.qmd
#        text: Games
      - text: Contact
        menu:
          - text: Contact Us
            href: contact.qmd
          - text: Request games
            href: contact-request.qmd
          - text: Submit game idea
            href: contact-idea.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/ghostCollective

format:
  html:
    theme: ghost.scss
    css: styles.css
    toc: false



